version: "3.9"

services:
  neo4j:
    image: neo4j:5-community
    container_name: neo4j-tour
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/testpassword
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data_2:/data
      - neo4j_logs_2:/logs

volumes:
  neo4j_data_2:
  neo4j_logs_2:
